name: Minify Calendarize Script
run-name: Minify calendarize.js for optimization 🚀
on:
  push:
    paths:
      - 'calendarize.js'
jobs:
  Minify-Calendarize-Script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Auto Minify
        uses: nizarmah/auto-minify@v3
        with:
          maxdepth: 0 # Only minify the root directory (where calendarize.js is)

      - name: Copy script to extension
        run: cp calendarize.min.js chrome-extension/calendarize.min.js

      - name: Committing minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'GitHub Action: Minify & add calendarize.min.js'
